// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Server.Models
{
    public partial class Card
    {
        public int Id { get; set; }
        public string SubType { get; set; }
        public int? Cost { get; set; }
        public string Text { get; set; }
        public string Rarity { get; set; }
        public string Type { get; set; }
        public string Quality { get; set; }
        public string Abilities { get; set; }
    }
}