// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Server.Models
{
    public partial class UserCard
    {
        public string User { get; set; }
        public int CardId { get; set; }
        public long Id { get; set; }
    }
}